### ISSUE TITLE
The name of Index and the name of the page is not the same

### ISSUE THREAD

**Issue by AvatarRolon** [MicrosoftDocs/windowsserverdocs.es-es#1]
Hi, I notice that the name in spanish under the index is "Apéndice D: Protección de cuentas de administrador integrada en Active Directory", while the name in the page in spanish is "Apéndice A: Protección de cuentas de administrador integrada en Active Directory" thats the unique problema i saw.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8499f8c0-64c7-2b6e-9022-115ed3d69904
* Version Independent ID: 9bf515dd-a4e4-baf2-8c18-0d0d76dd5eb0
* Content: [Apéndice D - protección de cuentas de administrador integrada en Active Directory](https://docs.microsoft.com/es-es/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs.es-es/blob/live/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by CeciAc** [comment]
Hello, @AvatarRolon 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by AvatarRolon** [comment]
Thank you for notice me, and take my comments to improve!!!!

**Comment by CeciAc** [comment]
Hello, @AvatarRolon 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
