### ISSUE TITLE
No funciona ningún ejemplo de la documentación de la orden forfiles

### ISSUE THREAD

**Issue by ihavenomouth** [MicrosoftDocs/windowsserverdocs.es-es#3]
A todos los ejemplos les falta la doble comilla que hace que funcione.
(The double quote is missing in all the examples).

Por ejemplo (e.g.):
```
forfiles /s /m *.* /d -01/01/2007 /c cmd /c echo @file is outdated. 
forfiles /s /m *.* /c cmd /c echo The extension of @file is 0x09@ext 
```

Deberían ser (They should be):
```
forfiles /s /m *.* /d -01/01/2007 /c "cmd /c echo @file is outdated. "
forfiles /s /m *.* /c "cmd /c echo The extension of @file is 0x09@ext "
```

File:
[https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/forfiles](https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/forfiles)

**Comment by srvbpigh** [comment]
Hello, @ihavenomouth
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @ihavenomouth 

Agradecemos enormemente su colaboración. El equipo ha revisado sus comentarios y parece que el problema ya se ha registrado.  

Revise el problema n.º https://github.com/MicrosoftDocs/windowsserverdocs/issues/4198
Por este motivo, se cerrará el problema, ya que está duplicado.  

Atentamente,

Equipo internacional de Microsoft Docs
