### ISSUE TITLE
Asociar varios Unidades organizativas a un grupo de red 

### ISSUE THREAD

**Issue by juankiz123** [MicrosoftDocs/windowsserverdocs.es-es#4]
Existe la posibilidad de agregar un solo grupo de red varios Unidades Organizativa

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f7b785b5-2b5f-9ec0-d429-49e01d45b35e
* Version Independent ID: 350db306-e299-1206-4d5b-f6e76da396af
* Content: [Revisar los conceptos de diseño de unidad organizativa](https://docs.microsoft.com/es-es/windows-server/identity/ad-ds/plan/reviewing-ou-design-concepts#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Reviewing-OU-Design-Concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs.es-es/blob/live/WindowsServerDocs/identity/ad-ds/plan/Reviewing-OU-Design-Concepts.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @juankiz123
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @juankiz123:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/windowsserverdocs/issues/4300.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
