### ISSUE TITLE
Error  al inicializar Disco Windows server 2003 si perder datos 

### ISSUE THREAD

**Issue by tuxnel1** [MicrosoftDocs/windowsserverdocs.es-es#5]
Buenas     soy nuevo en esto 
 A ver si me podéis ayudar, tengo un disco no inicializado en Windows server 2003    dicha unidad contiene información valiosa la he intentado inicializarlo, pero consigo el siguiente error :

no se puede completar la operación compruebe el registro de sucesos del sistema para obtener más información inicializar disco

 alguien me puede indicar   como acceder al disco ya que el contenido es de gran valor 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d347f950-4249-15da-2b61-6cc51f5fbb28
* Version Independent ID: cce0393d-b49e-0530-c4c1-679763ab61bf
* Content: [Solución de problemas de Administración de discos](https://docs.microsoft.com/es-es/windows-server/storage/disk-management/troubleshooting-disk-management?source=docs)
* Content Source: [WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md](https://github.com/MicrosoftDocs/windowsserverdocs.es-es/blob/live/WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @tuxnel1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @tuxnel1 

Gracias por su contribución. Sin embargo, estos comentarios están relacionados con el producto. Para registrar su sugerencia, haga clic en el botón «Proporcionar comentarios del producto» en la parte inferior de la página de DOCS. 

Si tiene algún comentario relacionado con la documentación, no dude en registrarlo a través de este canal. 

Apreciamos mucho su contribución a nuestros artículos. 

Equipo internacional de Microsoft DOCS
